version: '3.9'
name: nftsea-io

services:
  server:
    build: ./server
    container_name: nftsea-server
    env_file:
      - .env
    ports:
      - "4000:4000"
      
  client:
    build: ./client
    container_name: nftsea-client
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - server
