version: '3.9'
name: nftsea

services:
  server:
    build: ./server
    container_name: nftsea-server
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    container_name: nftsea-client
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - './client/src:/client/src'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - server
